# https://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    # Yarn doesn't support node@4
    # - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 10
    - nodejs_version: 12
    - nodejs_version: 13

clone_depth: 10

version: '{build}'
build: off
deploy: off

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --ignore-engines

cache:
  - node_modules -> appveyor.yml,package.json,yarn.lock
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml,package.json,yarn.lock'

test_script:
  - node --version
  - npm --version
  - cmd: 'yarn test:ci'
